### PR TITLE
Add load-from-gstatic strategy to slideshow.

### PR DESCRIPTION
**Pull request by applmak**
Also, example of use thanks to google cultural institute scans.

### CODE REVIEW

**Comment by plural** [comment]
why is this a gstatic strategy vs. a culturalinstitute strategy?  How many things a) are served from gstatic and b) have a consistent JSON format?

**Comment by applmak** [comment]
/me shrugs. I can rename it to anything you wish.

**Comment by plural** [comment]
i guess a broader question is does this belong in the chicago-brick repo or is this a particular implementation detail for the cultural institute module we have running in our office?

**Comment by applmak** [comment]
I think any image served from gstatic will have the same cgi parameters (e.g. =s1200-rw).

**Pull request closed without merging**
