### PR TITLE
feat: add new penrose_tiles module with testonly=true; improve shell scripts a bit

### PR DESCRIPTION
**Pull request by aarestad**
Creates a new `penrose_tiles` module with testonly set - I am hoping to be able to do a "live" test of this soon (next week maybe?) and need guidance as to how to do that. Also updates the run scripts to allow the user to set the `CHROME` env variable outside of the script.

Future work:

- some sort of constant zoom so we can go beyond 7 iterations without creating zillions of tiles
- some sort of animated transition between iterations

### CODE REVIEW

**Review by g-harel — APPROVED** [review]
Thanks for your contribution! I know this hasn't been the norm previously, but I'd appreciate some kind of screenshot to show what this module looks like to be included in the module directory!

**Comment by g-harel** [comment]
As far as live tests, maybe we can schedule something next week! I'll message you on crop chat.

**Comment by aarestad** [comment]
Should be ready to merge now?

**Comment by g-harel** [comment]
Yep, go ahead!

**Comment by aarestad** [comment]
I actually do not have merge permission :( "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Pull request merged**
